version: "3.8"

services:
  dime-db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: "dime"
      POSTGRES_PASSWORD: "D1M3@2024"
    ports:
      - "5432:5432"
  redis-database:
    image: redis:latest
    command: redis-server
    expose:
      - '6379'
    networks:
      - dime-network
    ports:
      - 6379:6379
networks:
  dime-network:
    driver: bridge